import pandas as pd
import os
from src.utils.drive_operations import upload_multiple_files, verify_drive_connection
from src.utils.utils_functions import record_successful_run, enforce_snake_case
from src.sources_processing.nutrilio.nutrilio_processing import full_nutrilio_pipeline


# ============================================================================
# DATA LOADING FUNCTIONS
# ============================================================================

def load_nutrilio_nutrition_data():
    """
    Load Nutrilio nutrition data (meal rows only).

    Returns:
        DataFrame: Nutrilio nutrition data with meal-level granularity
    """
    nutrilio_path = 'files/source_processed_files/nutrilio/nutrilio_nutrition_processed.csv'

    if not os.path.exists(nutrilio_path):
        print(f"❌ Nutrilio nutrition file not found: {nutrilio_path}")
        return None

    print(f"🥗 Loading Nutrilio nutrition data...")
    df = pd.read_csv(nutrilio_path, sep='|', encoding='utf-8')

    # Parse date
    df['date'] = pd.to_datetime(df['date'])

    print(f"✅ Loaded Nutrilio: {len(df):,} meal records")
    print(f"   Date range: {df['date'].min()} to {df['date'].max()}")

    # Display meal type breakdown
    if 'meal' in df.columns:
        meal_counts = df['meal'].value_counts()
        print(f"   Meal breakdown:")
        for meal_type, count in meal_counts.items():
            print(f"      • {meal_type}: {count:,}")

    return df


# ============================================================================
# PROCESSING FUNCTIONS
# ============================================================================

def create_nutrition_files():
    """
    Main processing function that loads nutrition data from sources and generates output files.

    Currently supports:
    - Nutrilio nutrition data (meals)

    Future sources could include:
    - MyFitnessPal
    - Cronometer
    - Other nutrition tracking apps

    Returns:
        bool: True if successful, False otherwise
    """
    print("\n" + "="*70)
    print("🥗 NUTRITION DATA PROCESSING")
    print("="*70)

    try:
        # STEP 1: Load Nutrilio nutrition data
        print("\n📊 STEP 1: Loading nutrition data from sources...")
        nutrilio_df = load_nutrilio_nutrition_data()

        if nutrilio_df is None or len(nutrilio_df) == 0:
            print("❌ No nutrition data loaded from sources")
            return False

        # STEP 2: Process and merge (currently only one source, but ready for multi-source)
        print("\n🔗 STEP 2: Processing nutrition data...")

        # Start with Nutrilio data as base
        nutrition_df = nutrilio_df.copy()

        # Add any additional processing here
        # For example: calculate daily totals, nutritional summaries, etc.

        # STEP 3: Sort by date and time (most recent first)
        print("\n📋 STEP 3: Sorting data...")
        nutrition_df = nutrition_df.sort_values(['date', 'time'], ascending=[False, False])

        # STEP 4: Enforce snake_case
        print("\n🔤 STEP 4: Enforcing snake_case column names...")
        nutrition_df = enforce_snake_case(nutrition_df, "nutrition_processed")

        # STEP 5: Save processed file
        print("\n💾 STEP 5: Saving processed files...")
        nutrition_dir = 'files/topic_processed_files/nutrition'
        os.makedirs(nutrition_dir, exist_ok=True)

        # Main nutrition file
        nutrition_output = f'{nutrition_dir}/nutrition_processed.csv'
        nutrition_df.to_csv(nutrition_output, sep='|', index=False, encoding='utf-8')

        print(f"✅ Saved nutrition data: {len(nutrition_df):,} records")
        print(f"   Output: {nutrition_output}")

        return True

    except Exception as e:
        print(f"\n❌ Error processing nutrition data: {e}")
        import traceback
        traceback.print_exc()
        return False


def upload_nutrition_results():
    """
    Uploads processed nutrition files to Google Drive.

    Returns:
        bool: True if successful, False otherwise
    """
    print("\n☁️  Uploading nutrition results to Google Drive...")

    files_to_upload = [
        "files/topic_processed_files/nutrition/nutrition_processed.csv",
        "files/website_files/nutrition/nutrition_page_data.csv"  # Website file (already generated by Nutrilio source)
    ]

    # Filter to only existing files
    existing_files = [f for f in files_to_upload if os.path.exists(f)]

    if not existing_files:
        print("❌ No files found to upload")
        return False

    print(f"📤 Uploading {len(existing_files)} file(s)...")
    for f in existing_files:
        print(f"   • {f}")

    success = upload_multiple_files(existing_files)

    if success:
        print("✅ Nutrition results uploaded successfully!")
    else:
        print("❌ Some files failed to upload")

    return success


# ============================================================================
# PIPELINE FUNCTIONS
# ============================================================================

def full_nutrition_pipeline(auto_full=False, auto_process_only=False):
    """
    Complete Nutrition TOPIC COORDINATOR pipeline.

    Options:
    1. Full pipeline (download → process sources → merge → upload)
    2. Process existing data and upload to Drive
    3. Upload existing processed files to Drive

    Args:
        auto_full (bool): If True, automatically runs option 1 without user input
        auto_process_only (bool): If True, automatically runs option 2 without user input

    Returns:
        bool: True if pipeline completed successfully, False otherwise
    """
    print("\n" + "="*70)
    print("🥗 NUTRITION TOPIC COORDINATOR PIPELINE")
    print("="*70)

    if auto_process_only:
        print("🤖 Auto process mode: Processing existing data and uploading...")
        choice = "2"
    elif auto_full:
        print("🤖 Auto mode: Running full pipeline...")
        choice = "1"
    else:
        print("\nSelect an option:")
        print("1. Full pipeline (download → process sources → merge → upload)")
        print("2. Process existing data and upload to Drive")
        print("3. Upload existing processed files to Drive")

        choice = input("\nEnter your choice (1-3): ").strip()

    success = False

    if choice == "1":
        print("\n🚀 Option 1: Full pipeline...")

        # Step 1: Run Nutrilio source pipeline
        print("\n🥗 Step 1/3: Processing Nutrilio nutrition data...")
        try:
            nutrilio_success = full_nutrilio_pipeline(auto_full=True)
            if not nutrilio_success:
                print("❌ Nutrilio pipeline failed, stopping nutrition coordination pipeline")
                return False
        except Exception as e:
            print(f"❌ Error in Nutrilio pipeline: {e}")
            return False

        # Step 2: Merge nutrition data
        print("\n🔗 Step 2/3: Merging nutrition data...")
        process_success = create_nutrition_files()
        if not process_success:
            print("❌ Nutrition data merge failed, stopping pipeline")
            return False

        # Step 3: Upload results
        print("\n☁️  Step 3/3: Uploading results...")
        success = upload_nutrition_results()

    elif choice == "2":
        print("\n⚙️  Option 2: Process existing data and upload...")
        print("   (Merges already-processed source files)")

        # Merge nutrition data from existing processed files
        process_success = create_nutrition_files()

        if process_success:
            success = upload_nutrition_results()
        else:
            print("❌ Processing failed, skipping upload")
            success = False

    elif choice == "3":
        print("\n☁️  Option 3: Upload existing processed files...")
        success = upload_nutrition_results()

    else:
        print("❌ Invalid choice. Please select 1-3.")
        return False

    # Final status
    print("\n" + "="*70)
    if success:
        print("✅ Nutrition topic coordinator completed successfully!")
        print("📊 Your nutrition dataset is ready for analysis!")
        # Record successful run
        record_successful_run('topic_nutrition', 'active')
    else:
        print("❌ Nutrition coordination pipeline failed")
    print("="*70)

    return success


if __name__ == "__main__":
    # Allow running this file directly
    print("🥗 Nutrition Topic Coordinator")
    print("This tool coordinates nutrition data from multiple sources.")

    # Test drive connection first
    if not verify_drive_connection():
        print("⚠️  Warning: Google Drive connection issues detected")
        proceed = input("Continue anyway? (Y/N): ").upper() == 'Y'
        if not proceed:
            exit()

    # Run the pipeline
    full_nutrition_pipeline(auto_full=False)
